Fix slack signing body decoding
pyslackers/sir-bot-a-lot-2 pull request #31
Opened 2018-11-27 19:54 UTC by Latent-Logic

... Well, this is where I look the fool ...
I just tested with the merged PR #30 and found I wasn't
decoding the body of incoming requests properly.

When I originally built this I had worked with a `slack-sansio`
diff to perform the decoding inside of `validate_request_signature`
but when I moved over to writing the tests here I switched to the
upstream `slack-sansio` without the change and wrote the tests for
that incorrect behavior. This fixes the issue entirely within sirbot.

The alternative solution is to update both `slack-sansio` and this
library at the same time to match my original diff there.

2018-11-27 20:01 UTC, ovv requested changes
No problems it happens. Good lesson for me to always do tests :D 

Thanks for catching & fixing it. Just a small nitpick and :shipit:

2018-11-27 20:01 UTC, ovv commented on sirbot/plugins/slack/endpoints.py
> +                    (await request.read()).decode("utf-8"),
I nerve like this syntax around `await` with parenthesis. in find it more readable to do that in two steps.

2018-11-28 23:08 UTC, Latent-Logic commented
Please test as well, but as a note this code has been running for the past 24hrs talking with slack successfully.

2018-11-29 17:26 UTC, ovv commented
Great thanks for your contribution

2018-11-29 17:26 UTC, ovv approved these changes

2018-11-29 17:26 UTC, merged